---

- name: Create Arista Trunking CFGS 
  hosts: arista
  
  tasks:
    - name: Setting Ethernet3 to trunk 
      eos_switchport: name=Ethernet3 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=997,998,999 
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{eapi_port }}
           transport=https

    - name: Write to NVRAM memory 
      eos_command: commands="write memory"
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{eapi_port }}
           transport=https


