---

- name: Reset all configurations 
  hosts: arista
  
  tasks:
    - name: Set Ethernet3 to access mode, VLAN 1
      eos_switchport: name={{ item }} mode=access access_vlan=1 trunk_allowed_vlans=1-4096 trunk_native_vlan=1
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{eapi_port }}
           transport=https
      with_items:
          - Ethernet3

    - name: Setting Ethernet3 description
      eos_interface: name=Ethernet3 description=""
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{eapi_port }}
           transport=https


    - name: Remove VLANs
      eos_vlan: name={{ item.name }} vlanid={{item.vlanid}} state=absent
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{eapi_port }}
           transport=https
      with_items:
        - {name: GmazBLUE, vlanid: 997}
        - {name: GmazRED, vlanid: 998}
        - {name: GmazGREEN, vlanid: 999}

    - name: Write to NVRAM memory 
      eos_command: commands="write memory"
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{eapi_port }}
           transport=https

